#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photocopy.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_Photocopy")]
	public partial class PhotocopyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSale(Sale instance);
    partial void UpdateSale(Sale instance);
    partial void DeleteSale(Sale instance);
    partial void InsertVisit(Visit instance);
    partial void UpdateVisit(Visit instance);
    partial void DeleteVisit(Visit instance);
    partial void InsertRelatedNew(RelatedNew instance);
    partial void UpdateRelatedNew(RelatedNew instance);
    partial void DeleteRelatedNew(RelatedNew instance);
    partial void InsertOption(Option instance);
    partial void UpdateOption(Option instance);
    partial void DeleteOption(Option instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    partial void InsertNhaSanXuat(NhaSanXuat instance);
    partial void UpdateNhaSanXuat(NhaSanXuat instance);
    partial void DeleteNhaSanXuat(NhaSanXuat instance);
    partial void InsertTinTuc(TinTuc instance);
    partial void UpdateTinTuc(TinTuc instance);
    partial void DeleteTinTuc(TinTuc instance);
    partial void InsertTechniqueSupport(TechniqueSupport instance);
    partial void UpdateTechniqueSupport(TechniqueSupport instance);
    partial void DeleteTechniqueSupport(TechniqueSupport instance);
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public PhotocopyDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_PhotocopyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PhotocopyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhotocopyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhotocopyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhotocopyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sale> Sales
		{
			get
			{
				return this.GetTable<Sale>();
			}
		}
		
		public System.Data.Linq.Table<Visit> Visits
		{
			get
			{
				return this.GetTable<Visit>();
			}
		}
		
		public System.Data.Linq.Table<RelatedNew> RelatedNews
		{
			get
			{
				return this.GetTable<RelatedNew>();
			}
		}
		
		public System.Data.Linq.Table<Option> Options
		{
			get
			{
				return this.GetTable<Option>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<NhaSanXuat> NhaSanXuats
		{
			get
			{
				return this.GetTable<NhaSanXuat>();
			}
		}
		
		public System.Data.Linq.Table<TinTuc> TinTucs
		{
			get
			{
				return this.GetTable<TinTuc>();
			}
		}
		
		public System.Data.Linq.Table<TechniqueSupport> TechniqueSupports
		{
			get
			{
				return this.GetTable<TechniqueSupport>();
			}
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sale")]
	public partial class Sale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SaleID;
		
		private int _SanPhamID;
		
		private int _GiaGiam;
		
		private System.DateTime _NgayApDung;
		
		private System.DateTime _NgayHetHan;
		
		private EntityRef<SanPham> _SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSaleIDChanging(int value);
    partial void OnSaleIDChanged();
    partial void OnSanPhamIDChanging(int value);
    partial void OnSanPhamIDChanged();
    partial void OnGiaGiamChanging(int value);
    partial void OnGiaGiamChanged();
    partial void OnNgayApDungChanging(System.DateTime value);
    partial void OnNgayApDungChanged();
    partial void OnNgayHetHanChanging(System.DateTime value);
    partial void OnNgayHetHanChanged();
    #endregion
		
		public Sale()
		{
			this._SanPham = default(EntityRef<SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SaleID
		{
			get
			{
				return this._SaleID;
			}
			set
			{
				if ((this._SaleID != value))
				{
					this.OnSaleIDChanging(value);
					this.SendPropertyChanging();
					this._SaleID = value;
					this.SendPropertyChanged("SaleID");
					this.OnSaleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPhamID", DbType="Int NOT NULL")]
		public int SanPhamID
		{
			get
			{
				return this._SanPhamID;
			}
			set
			{
				if ((this._SanPhamID != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSanPhamIDChanging(value);
					this.SendPropertyChanging();
					this._SanPhamID = value;
					this.SendPropertyChanged("SanPhamID");
					this.OnSanPhamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaGiam", DbType="Int NOT NULL")]
		public int GiaGiam
		{
			get
			{
				return this._GiaGiam;
			}
			set
			{
				if ((this._GiaGiam != value))
				{
					this.OnGiaGiamChanging(value);
					this.SendPropertyChanging();
					this._GiaGiam = value;
					this.SendPropertyChanged("GiaGiam");
					this.OnGiaGiamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayApDung", DbType="Date NOT NULL")]
		public System.DateTime NgayApDung
		{
			get
			{
				return this._NgayApDung;
			}
			set
			{
				if ((this._NgayApDung != value))
				{
					this.OnNgayApDungChanging(value);
					this.SendPropertyChanging();
					this._NgayApDung = value;
					this.SendPropertyChanged("NgayApDung");
					this.OnNgayApDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="Date NOT NULL")]
		public System.DateTime NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_Sale", Storage="_SanPham", ThisKey="SanPhamID", OtherKey="SanPhamID", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.Sales.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.Sales.Add(this);
						this._SanPhamID = value.SanPhamID;
					}
					else
					{
						this._SanPhamID = default(int);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Visit")]
	public partial class Visit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VisitID;
		
		private int _pageviews;
		
		private int _useronline;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVisitIDChanging(int value);
    partial void OnVisitIDChanged();
    partial void OnpageviewsChanging(int value);
    partial void OnpageviewsChanged();
    partial void OnuseronlineChanging(int value);
    partial void OnuseronlineChanged();
    #endregion
		
		public Visit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VisitID
		{
			get
			{
				return this._VisitID;
			}
			set
			{
				if ((this._VisitID != value))
				{
					this.OnVisitIDChanging(value);
					this.SendPropertyChanging();
					this._VisitID = value;
					this.SendPropertyChanged("VisitID");
					this.OnVisitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageviews", DbType="Int NOT NULL")]
		public int pageviews
		{
			get
			{
				return this._pageviews;
			}
			set
			{
				if ((this._pageviews != value))
				{
					this.OnpageviewsChanging(value);
					this.SendPropertyChanging();
					this._pageviews = value;
					this.SendPropertyChanged("pageviews");
					this.OnpageviewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_useronline", DbType="Int NOT NULL")]
		public int useronline
		{
			get
			{
				return this._useronline;
			}
			set
			{
				if ((this._useronline != value))
				{
					this.OnuseronlineChanging(value);
					this.SendPropertyChanging();
					this._useronline = value;
					this.SendPropertyChanged("useronline");
					this.OnuseronlineChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RelatedNews")]
	public partial class RelatedNew : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RelatedNewsID;
		
		private System.Nullable<int> _SanPhamID;
		
		private string _RelatedNewsName;
		
		private string _RelatedNewsLink;
		
		private System.Nullable<int> _TinTucID;
		
		private bool _EnableRN;
		
		private EntityRef<SanPham> _SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRelatedNewsIDChanging(int value);
    partial void OnRelatedNewsIDChanged();
    partial void OnSanPhamIDChanging(System.Nullable<int> value);
    partial void OnSanPhamIDChanged();
    partial void OnRelatedNewsNameChanging(string value);
    partial void OnRelatedNewsNameChanged();
    partial void OnRelatedNewsLinkChanging(string value);
    partial void OnRelatedNewsLinkChanged();
    partial void OnTinTucIDChanging(System.Nullable<int> value);
    partial void OnTinTucIDChanged();
    partial void OnEnableRNChanging(bool value);
    partial void OnEnableRNChanged();
    #endregion
		
		public RelatedNew()
		{
			this._SanPham = default(EntityRef<SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedNewsID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RelatedNewsID
		{
			get
			{
				return this._RelatedNewsID;
			}
			set
			{
				if ((this._RelatedNewsID != value))
				{
					this.OnRelatedNewsIDChanging(value);
					this.SendPropertyChanging();
					this._RelatedNewsID = value;
					this.SendPropertyChanged("RelatedNewsID");
					this.OnRelatedNewsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPhamID", DbType="Int")]
		public System.Nullable<int> SanPhamID
		{
			get
			{
				return this._SanPhamID;
			}
			set
			{
				if ((this._SanPhamID != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSanPhamIDChanging(value);
					this.SendPropertyChanging();
					this._SanPhamID = value;
					this.SendPropertyChanged("SanPhamID");
					this.OnSanPhamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedNewsName", DbType="NVarChar(500)")]
		public string RelatedNewsName
		{
			get
			{
				return this._RelatedNewsName;
			}
			set
			{
				if ((this._RelatedNewsName != value))
				{
					this.OnRelatedNewsNameChanging(value);
					this.SendPropertyChanging();
					this._RelatedNewsName = value;
					this.SendPropertyChanged("RelatedNewsName");
					this.OnRelatedNewsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedNewsLink", DbType="NVarChar(500)")]
		public string RelatedNewsLink
		{
			get
			{
				return this._RelatedNewsLink;
			}
			set
			{
				if ((this._RelatedNewsLink != value))
				{
					this.OnRelatedNewsLinkChanging(value);
					this.SendPropertyChanging();
					this._RelatedNewsLink = value;
					this.SendPropertyChanged("RelatedNewsLink");
					this.OnRelatedNewsLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinTucID", DbType="Int")]
		public System.Nullable<int> TinTucID
		{
			get
			{
				return this._TinTucID;
			}
			set
			{
				if ((this._TinTucID != value))
				{
					this.OnTinTucIDChanging(value);
					this.SendPropertyChanging();
					this._TinTucID = value;
					this.SendPropertyChanged("TinTucID");
					this.OnTinTucIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableRN", DbType="Bit NOT NULL")]
		public bool EnableRN
		{
			get
			{
				return this._EnableRN;
			}
			set
			{
				if ((this._EnableRN != value))
				{
					this.OnEnableRNChanging(value);
					this.SendPropertyChanging();
					this._EnableRN = value;
					this.SendPropertyChanged("EnableRN");
					this.OnEnableRNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_RelatedNew", Storage="_SanPham", ThisKey="SanPhamID", OtherKey="SanPhamID", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.RelatedNews.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.RelatedNews.Add(this);
						this._SanPhamID = value.SanPhamID;
					}
					else
					{
						this._SanPhamID = default(Nullable<int>);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Option]")]
	public partial class Option : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OptionID;
		
		private System.Nullable<int> _SanPhamID;
		
		private string _OptionName;
		
		private string _OptionDescription;
		
		private System.Nullable<bool> _EnableOp;
		
		private EntityRef<SanPham> _SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOptionIDChanging(int value);
    partial void OnOptionIDChanged();
    partial void OnSanPhamIDChanging(System.Nullable<int> value);
    partial void OnSanPhamIDChanged();
    partial void OnOptionNameChanging(string value);
    partial void OnOptionNameChanged();
    partial void OnOptionDescriptionChanging(string value);
    partial void OnOptionDescriptionChanged();
    partial void OnEnableOpChanging(System.Nullable<bool> value);
    partial void OnEnableOpChanged();
    #endregion
		
		public Option()
		{
			this._SanPham = default(EntityRef<SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OptionID
		{
			get
			{
				return this._OptionID;
			}
			set
			{
				if ((this._OptionID != value))
				{
					this.OnOptionIDChanging(value);
					this.SendPropertyChanging();
					this._OptionID = value;
					this.SendPropertyChanged("OptionID");
					this.OnOptionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPhamID", DbType="Int")]
		public System.Nullable<int> SanPhamID
		{
			get
			{
				return this._SanPhamID;
			}
			set
			{
				if ((this._SanPhamID != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSanPhamIDChanging(value);
					this.SendPropertyChanging();
					this._SanPhamID = value;
					this.SendPropertyChanged("SanPhamID");
					this.OnSanPhamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionName", DbType="NVarChar(100)")]
		public string OptionName
		{
			get
			{
				return this._OptionName;
			}
			set
			{
				if ((this._OptionName != value))
				{
					this.OnOptionNameChanging(value);
					this.SendPropertyChanging();
					this._OptionName = value;
					this.SendPropertyChanged("OptionName");
					this.OnOptionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionDescription", DbType="NVarChar(300)")]
		public string OptionDescription
		{
			get
			{
				return this._OptionDescription;
			}
			set
			{
				if ((this._OptionDescription != value))
				{
					this.OnOptionDescriptionChanging(value);
					this.SendPropertyChanging();
					this._OptionDescription = value;
					this.SendPropertyChanged("OptionDescription");
					this.OnOptionDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableOp", DbType="Bit")]
		public System.Nullable<bool> EnableOp
		{
			get
			{
				return this._EnableOp;
			}
			set
			{
				if ((this._EnableOp != value))
				{
					this.OnEnableOpChanging(value);
					this.SendPropertyChanging();
					this._EnableOp = value;
					this.SendPropertyChanged("EnableOp");
					this.OnEnableOpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_Option", Storage="_SanPham", ThisKey="SanPhamID", OtherKey="SanPhamID", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.Options.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.Options.Add(this);
						this._SanPhamID = value.SanPhamID;
					}
					else
					{
						this._SanPhamID = default(Nullable<int>);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SanPhamID;
		
		private string _MaSanPham;
		
		private string _MaSanXuat;
		
		private string _TenSanPham;
		
		private string _LoaiMay;
		
		private decimal _DonGia;
		
		private System.Nullable<System.DateTime> _NgayNhapHang;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<bool> _ChoThue;
		
		private System.Nullable<bool> _Hot;
		
		private System.Nullable<int> _LuotXem;
		
		private string _Gia;
		
		private string _HinhAnh;
		
		private System.Nullable<bool> _EnableP;
		
		private EntitySet<Sale> _Sales;
		
		private EntitySet<RelatedNew> _RelatedNews;
		
		private EntitySet<Option> _Options;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSanPhamIDChanging(int value);
    partial void OnSanPhamIDChanged();
    partial void OnMaSanPhamChanging(string value);
    partial void OnMaSanPhamChanged();
    partial void OnMaSanXuatChanging(string value);
    partial void OnMaSanXuatChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnLoaiMayChanging(string value);
    partial void OnLoaiMayChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    partial void OnNgayNhapHangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapHangChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnChoThueChanging(System.Nullable<bool> value);
    partial void OnChoThueChanged();
    partial void OnHotChanging(System.Nullable<bool> value);
    partial void OnHotChanged();
    partial void OnLuotXemChanging(System.Nullable<int> value);
    partial void OnLuotXemChanged();
    partial void OnGiaChanging(string value);
    partial void OnGiaChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnEnablePChanging(System.Nullable<bool> value);
    partial void OnEnablePChanged();
    #endregion
		
		public SanPham()
		{
			this._Sales = new EntitySet<Sale>(new Action<Sale>(this.attach_Sales), new Action<Sale>(this.detach_Sales));
			this._RelatedNews = new EntitySet<RelatedNew>(new Action<RelatedNew>(this.attach_RelatedNews), new Action<RelatedNew>(this.detach_RelatedNews));
			this._Options = new EntitySet<Option>(new Action<Option>(this.attach_Options), new Action<Option>(this.detach_Options));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPhamID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SanPhamID
		{
			get
			{
				return this._SanPhamID;
			}
			set
			{
				if ((this._SanPhamID != value))
				{
					this.OnSanPhamIDChanging(value);
					this.SendPropertyChanging();
					this._SanPhamID = value;
					this.SendPropertyChanged("SanPhamID");
					this.OnSanPhamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="NVarChar(50)")]
		public string MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanXuat", DbType="NVarChar(50)")]
		public string MaSanXuat
		{
			get
			{
				return this._MaSanXuat;
			}
			set
			{
				if ((this._MaSanXuat != value))
				{
					this.OnMaSanXuatChanging(value);
					this.SendPropertyChanging();
					this._MaSanXuat = value;
					this.SendPropertyChanged("MaSanXuat");
					this.OnMaSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(50)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiMay", DbType="NVarChar(50)")]
		public string LoaiMay
		{
			get
			{
				return this._LoaiMay;
			}
			set
			{
				if ((this._LoaiMay != value))
				{
					this.OnLoaiMayChanging(value);
					this.SendPropertyChanging();
					this._LoaiMay = value;
					this.SendPropertyChanged("LoaiMay");
					this.OnLoaiMayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money NOT NULL")]
		public decimal DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhapHang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhapHang
		{
			get
			{
				return this._NgayNhapHang;
			}
			set
			{
				if ((this._NgayNhapHang != value))
				{
					this.OnNgayNhapHangChanging(value);
					this.SendPropertyChanging();
					this._NgayNhapHang = value;
					this.SendPropertyChanged("NgayNhapHang");
					this.OnNgayNhapHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoThue", DbType="Bit")]
		public System.Nullable<bool> ChoThue
		{
			get
			{
				return this._ChoThue;
			}
			set
			{
				if ((this._ChoThue != value))
				{
					this.OnChoThueChanging(value);
					this.SendPropertyChanging();
					this._ChoThue = value;
					this.SendPropertyChanged("ChoThue");
					this.OnChoThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hot", DbType="Bit")]
		public System.Nullable<bool> Hot
		{
			get
			{
				return this._Hot;
			}
			set
			{
				if ((this._Hot != value))
				{
					this.OnHotChanging(value);
					this.SendPropertyChanging();
					this._Hot = value;
					this.SendPropertyChanged("Hot");
					this.OnHotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
		public System.Nullable<int> LuotXem
		{
			get
			{
				return this._LuotXem;
			}
			set
			{
				if ((this._LuotXem != value))
				{
					this.OnLuotXemChanging(value);
					this.SendPropertyChanging();
					this._LuotXem = value;
					this.SendPropertyChanged("LuotXem");
					this.OnLuotXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="NVarChar(50)")]
		public string Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableP", DbType="Bit")]
		public System.Nullable<bool> EnableP
		{
			get
			{
				return this._EnableP;
			}
			set
			{
				if ((this._EnableP != value))
				{
					this.OnEnablePChanging(value);
					this.SendPropertyChanging();
					this._EnableP = value;
					this.SendPropertyChanged("EnableP");
					this.OnEnablePChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_Sale", Storage="_Sales", ThisKey="SanPhamID", OtherKey="SanPhamID")]
		public EntitySet<Sale> Sales
		{
			get
			{
				return this._Sales;
			}
			set
			{
				this._Sales.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_RelatedNew", Storage="_RelatedNews", ThisKey="SanPhamID", OtherKey="SanPhamID")]
		public EntitySet<RelatedNew> RelatedNews
		{
			get
			{
				return this._RelatedNews;
			}
			set
			{
				this._RelatedNews.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_Option", Storage="_Options", ThisKey="SanPhamID", OtherKey="SanPhamID")]
		public EntitySet<Option> Options
		{
			get
			{
				return this._Options;
			}
			set
			{
				this._Options.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sales(Sale entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_Sales(Sale entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
		
		private void attach_RelatedNews(RelatedNew entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_RelatedNews(RelatedNew entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
		
		private void attach_Options(Option entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_Options(Option entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaSanXuat")]
	public partial class NhaSanXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SanXuatID;
		
		private string _MaSanXuat;
		
		private string _TenSanXuat;
		
		private string _DiaChiSX;
		
		private string _DienThoaiSX;
		
		private string _Fax;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSanXuatIDChanging(int value);
    partial void OnSanXuatIDChanged();
    partial void OnMaSanXuatChanging(string value);
    partial void OnMaSanXuatChanged();
    partial void OnTenSanXuatChanging(string value);
    partial void OnTenSanXuatChanged();
    partial void OnDiaChiSXChanging(string value);
    partial void OnDiaChiSXChanged();
    partial void OnDienThoaiSXChanging(string value);
    partial void OnDienThoaiSXChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    #endregion
		
		public NhaSanXuat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanXuatID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SanXuatID
		{
			get
			{
				return this._SanXuatID;
			}
			set
			{
				if ((this._SanXuatID != value))
				{
					this.OnSanXuatIDChanging(value);
					this.SendPropertyChanging();
					this._SanXuatID = value;
					this.SendPropertyChanged("SanXuatID");
					this.OnSanXuatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanXuat", DbType="NVarChar(50)")]
		public string MaSanXuat
		{
			get
			{
				return this._MaSanXuat;
			}
			set
			{
				if ((this._MaSanXuat != value))
				{
					this.OnMaSanXuatChanging(value);
					this.SendPropertyChanging();
					this._MaSanXuat = value;
					this.SendPropertyChanged("MaSanXuat");
					this.OnMaSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanXuat", DbType="NChar(50)")]
		public string TenSanXuat
		{
			get
			{
				return this._TenSanXuat;
			}
			set
			{
				if ((this._TenSanXuat != value))
				{
					this.OnTenSanXuatChanging(value);
					this.SendPropertyChanging();
					this._TenSanXuat = value;
					this.SendPropertyChanged("TenSanXuat");
					this.OnTenSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiSX", DbType="NVarChar(100)")]
		public string DiaChiSX
		{
			get
			{
				return this._DiaChiSX;
			}
			set
			{
				if ((this._DiaChiSX != value))
				{
					this.OnDiaChiSXChanging(value);
					this.SendPropertyChanging();
					this._DiaChiSX = value;
					this.SendPropertyChanged("DiaChiSX");
					this.OnDiaChiSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiSX", DbType="NVarChar(20)")]
		public string DienThoaiSX
		{
			get
			{
				return this._DienThoaiSX;
			}
			set
			{
				if ((this._DienThoaiSX != value))
				{
					this.OnDienThoaiSXChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiSX = value;
					this.SendPropertyChanged("DienThoaiSX");
					this.OnDienThoaiSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuc")]
	public partial class TinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TinTucID;
		
		private string _TinTucTitle;
		
		private string _TinTucQuote;
		
		private string _TinTucImage;
		
		private System.Nullable<System.DateTime> _TinTucPostDate;
		
		private System.Nullable<bool> _TinTucHot;
		
		private string _TinTucContent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTinTucIDChanging(int value);
    partial void OnTinTucIDChanged();
    partial void OnTinTucTitleChanging(string value);
    partial void OnTinTucTitleChanged();
    partial void OnTinTucQuoteChanging(string value);
    partial void OnTinTucQuoteChanged();
    partial void OnTinTucImageChanging(string value);
    partial void OnTinTucImageChanged();
    partial void OnTinTucPostDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTinTucPostDateChanged();
    partial void OnTinTucHotChanging(System.Nullable<bool> value);
    partial void OnTinTucHotChanged();
    partial void OnTinTucContentChanging(string value);
    partial void OnTinTucContentChanged();
    #endregion
		
		public TinTuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinTucID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TinTucID
		{
			get
			{
				return this._TinTucID;
			}
			set
			{
				if ((this._TinTucID != value))
				{
					this.OnTinTucIDChanging(value);
					this.SendPropertyChanging();
					this._TinTucID = value;
					this.SendPropertyChanged("TinTucID");
					this.OnTinTucIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinTucTitle", DbType="NVarChar(100)")]
		public string TinTucTitle
		{
			get
			{
				return this._TinTucTitle;
			}
			set
			{
				if ((this._TinTucTitle != value))
				{
					this.OnTinTucTitleChanging(value);
					this.SendPropertyChanging();
					this._TinTucTitle = value;
					this.SendPropertyChanged("TinTucTitle");
					this.OnTinTucTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinTucQuote", DbType="NVarChar(500)")]
		public string TinTucQuote
		{
			get
			{
				return this._TinTucQuote;
			}
			set
			{
				if ((this._TinTucQuote != value))
				{
					this.OnTinTucQuoteChanging(value);
					this.SendPropertyChanging();
					this._TinTucQuote = value;
					this.SendPropertyChanged("TinTucQuote");
					this.OnTinTucQuoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinTucImage", DbType="NVarChar(200)")]
		public string TinTucImage
		{
			get
			{
				return this._TinTucImage;
			}
			set
			{
				if ((this._TinTucImage != value))
				{
					this.OnTinTucImageChanging(value);
					this.SendPropertyChanging();
					this._TinTucImage = value;
					this.SendPropertyChanged("TinTucImage");
					this.OnTinTucImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinTucPostDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TinTucPostDate
		{
			get
			{
				return this._TinTucPostDate;
			}
			set
			{
				if ((this._TinTucPostDate != value))
				{
					this.OnTinTucPostDateChanging(value);
					this.SendPropertyChanging();
					this._TinTucPostDate = value;
					this.SendPropertyChanged("TinTucPostDate");
					this.OnTinTucPostDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinTucHot", DbType="Bit")]
		public System.Nullable<bool> TinTucHot
		{
			get
			{
				return this._TinTucHot;
			}
			set
			{
				if ((this._TinTucHot != value))
				{
					this.OnTinTucHotChanging(value);
					this.SendPropertyChanging();
					this._TinTucHot = value;
					this.SendPropertyChanged("TinTucHot");
					this.OnTinTucHotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinTucContent", DbType="NVarChar(MAX)")]
		public string TinTucContent
		{
			get
			{
				return this._TinTucContent;
			}
			set
			{
				if ((this._TinTucContent != value))
				{
					this.OnTinTucContentChanging(value);
					this.SendPropertyChanging();
					this._TinTucContent = value;
					this.SendPropertyChanged("TinTucContent");
					this.OnTinTucContentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TechniqueSupport")]
	public partial class TechniqueSupport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TechniqueID;
		
		private string _TechniqueName;
		
		private string _TechniqueContent;
		
		private System.Nullable<System.DateTime> _PostDate;
		
		private System.Nullable<bool> _EnableT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTechniqueIDChanging(int value);
    partial void OnTechniqueIDChanged();
    partial void OnTechniqueNameChanging(string value);
    partial void OnTechniqueNameChanged();
    partial void OnTechniqueContentChanging(string value);
    partial void OnTechniqueContentChanged();
    partial void OnPostDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPostDateChanged();
    partial void OnEnableTChanging(System.Nullable<bool> value);
    partial void OnEnableTChanged();
    #endregion
		
		public TechniqueSupport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TechniqueID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TechniqueID
		{
			get
			{
				return this._TechniqueID;
			}
			set
			{
				if ((this._TechniqueID != value))
				{
					this.OnTechniqueIDChanging(value);
					this.SendPropertyChanging();
					this._TechniqueID = value;
					this.SendPropertyChanged("TechniqueID");
					this.OnTechniqueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TechniqueName", DbType="NVarChar(200)")]
		public string TechniqueName
		{
			get
			{
				return this._TechniqueName;
			}
			set
			{
				if ((this._TechniqueName != value))
				{
					this.OnTechniqueNameChanging(value);
					this.SendPropertyChanging();
					this._TechniqueName = value;
					this.SendPropertyChanged("TechniqueName");
					this.OnTechniqueNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TechniqueContent", DbType="NVarChar(MAX)")]
		public string TechniqueContent
		{
			get
			{
				return this._TechniqueContent;
			}
			set
			{
				if ((this._TechniqueContent != value))
				{
					this.OnTechniqueContentChanging(value);
					this.SendPropertyChanging();
					this._TechniqueContent = value;
					this.SendPropertyChanged("TechniqueContent");
					this.OnTechniqueContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PostDate
		{
			get
			{
				return this._PostDate;
			}
			set
			{
				if ((this._PostDate != value))
				{
					this.OnPostDateChanging(value);
					this.SendPropertyChanging();
					this._PostDate = value;
					this.SendPropertyChanged("PostDate");
					this.OnPostDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableT", DbType="Bit")]
		public System.Nullable<bool> EnableT
		{
			get
			{
				return this._EnableT;
			}
			set
			{
				if ((this._EnableT != value))
				{
					this.OnEnableTChanging(value);
					this.SendPropertyChanging();
					this._EnableT = value;
					this.SendPropertyChanged("EnableT");
					this.OnEnableTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerID;
		
		private string _CustomerName;
		
		private string _CustomerImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnCustomerImageChanging(string value);
    partial void OnCustomerImageChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(500)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this.OnCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerName = value;
					this.SendPropertyChanged("CustomerName");
					this.OnCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerImage", DbType="NVarChar(500)")]
		public string CustomerImage
		{
			get
			{
				return this._CustomerImage;
			}
			set
			{
				if ((this._CustomerImage != value))
				{
					this.OnCustomerImageChanging(value);
					this.SendPropertyChanging();
					this._CustomerImage = value;
					this.SendPropertyChanged("CustomerImage");
					this.OnCustomerImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Name;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private string _Gender;
		
		private string _Address;
		
		private string _Telephone;
		
		private string _Email;
		
		private string _Username;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdayChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="Date")]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this.OnBirthdayChanging(value);
					this.SendPropertyChanging();
					this._Birthday = value;
					this.SendPropertyChanged("Birthday");
					this.OnBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NChar(15)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
